# 构建
[build]
  command = "mkdir -p dist && cp -r img mihomo.yaml mihomo_smart.yaml mihomo.js mihomo_smart.js dist/"
  publish = "dist"

# 跨域
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "*"
    Access-Control-Allow-Headers = "*"
    Content-Security-Policy = "frame-ancestors *"

# 根目录跳转
[[redirects]]
  from = "/"
  to = "https://github.com/echs-top/proxy"
  status = 302
  force = true
