# 跨域
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "*"
    Access-Control-Allow-Headers = "*"

# 根目录跳转
[[redirects]]
  from = "/"
  to = "https://github.com/echs-top/proxy"
  status = 302
  force = true
